app = "encore-dia-beta-server"

primary_region = "mia"  

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"

# This is the corrected format for processes
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Health check
[http_service.checks]
  [http_service.checks.health]
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    method = "GET"
    path = "/health"