app = "encore-dia-beta-server"
primary_region = "mia"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[http_service.checks]]
  grace_period = "10s"
  interval = "10s"
  method = "GET"
  path = "/health"
  timeout = "2s"
